name: CI Pipeline - Build, Push Image to ECR, and Update AWS Batch Job Definition

on:
  push:
    branches:
      - main

jobs:
  build-push-update-batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        needs: build-push-update-batch

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        needs: Checkout Repository
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        needs:Configure AWS Credentials

      - name: Generate image name
        id: generate-image-name
        run: echo "::set-output name=image_name::awsbatch-${{ github.run_number }}"
        needs: Login to Amazon ECR

      - name: Create ECR Repository
        run: |
          aws ecr create-repository --repository-name ${{ steps.generate-image-name.outputs.image_name }} --region sa-east-1
        needs: Generate image name

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.generate-image-name.outputs.image_name }} .
        needs: Create ECR Repository

      - name: Tag Docker image
        run: docker tag ${{ steps.generate-image-name.outputs.image_name }} ${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name }}
        needs: Build Docker image
      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name }}

      - name: Update AWS Batch Job Definition
        needs: Tag Docker image
        run: |
          aws batch register-job-definition --job-definition-name YOUR_JOB_DEFINITION_NAME \
            --type container \
            --container-properties '{
              "image": "${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name }}",
              "vcpus": 1,
              "memory": 2048
            }'


            
