name: CI Pipeline - Build, Push Image to ECR, and Update AWS Batch Job Definition

on:
  push:
    branches:
      - main

jobs:
  build-push-update-batch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Generate image name
      id: generate-image-name
      run: echo "::set-output name=image_name_to_use::${GITHUB_REPOSITORY##*/}-$(date +'%Y%m%d%H%M%S')"

    - name: Build Docker image
      run: |
       docker build -t awsbatch-20240402011833 -f workflows/Dockerfile .

    - name: Tag Docker image
      run: docker tag ${{ steps.generate-image-name.outputs.image_name_to_use }} ${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name_to_use }}

    - name: Push Docker image to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name_to_use }}

    - name: Update AWS Batch Job Definition
      run: |
        aws batch register-job-definition --job-definition-name YOUR_JOB_DEFINITION_NAME \
          --type container \
          --container-properties '{
            "image": "${{ steps.login-ecr.outputs.registry }}/${{ steps.generate-image-name.outputs.image_name_to_use }}",
            "vcpus": YOUR_VCPUS,
            "memory": YOUR_MEMORY
          }'
